#!/usr/bin/env python3
"""
The media library: one manifest, one contact sheet per folder.

    python3 tools/media.py scan      rewrite MEDIA.tsv, keeping the captions
    python3 tools/media.py verify    every file against the manifest, and back
    python3 tools/media.py sheets    rebuild the CONTACT-SHEET.jpg files
    python3 tools/media.py show 04   print one folder's rows as a readable list

Why this exists. There are ninety-odd media files here and the survey cites them
by number: "photograph 34", "photographs 04 and 29". Before this, answering
"what is photograph 17?" meant opening a 3 MB file and looking. The folder with
the most citations, 04_plant-room, had no index of any kind.

MEDIA.tsv is the one home for what each file is. Everything in it except the
caption is computed from the file itself, so it cannot drift: scan recomputes,
verify compares, and tools/check.py C21 fails the build if the two disagree.
The caption is the one human column, and scan carries it forward.

EXIF ORIENTATION IS HONOURED AND NEVER BAKED IN. One file in here,
02_printed-sheets/05, came off the phone tagged "Rotate 270 CW". That tag is
correct and the pixels are the original bytes off the camera. Re-encoding it to
straighten it would trade real provenance for the convenience of tools that
ignore EXIF, which is the wrong trade in an archive. Everything here reads the
tag instead; the manifest records it; the folder's READ-ME says so.

Pillow is needed for sheets, and for the pixel dimensions of formats this file
cannot parse itself. scan and verify degrade to the built-in JPEG/PNG readers
when it is absent, which covers every image in the repository today.
"""

import os, re, sys, struct, hashlib, subprocess, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "MEDIA.tsv")
COLUMNS = ("path", "kind", "bytes", "pixels", "captured", "made", "sha256", "caption")

MEDIA_EXT = {
    ".jpg": "photo", ".jpeg": "photo", ".png": "image", ".webp": "image",
    ".mp4": "video", ".pdf": "document", ".glb": "model", ".svg": "image",
}
# apparatus rather than evidence: generated by this tool, indexed by nothing
SHEET = "CONTACT-SHEET.jpg"
SHEET_TAG = "contact-sheet-of:"      # written into the JPEG comment, read by C22
# 00_inbox is untracked staging; 01_survey is the deliverable and has its own
# integrity record in 01_survey/DERIVED.txt. The library is the numbered
# evidence folders, and root-level files are apparatus rather than evidence.
SKIP_DIRS = {".git", "node_modules", "00_inbox", "01_survey", "tools"}

HEADER = """\
# THE MEDIA LIBRARY, ONE ROW PER FILE
#
# Generated by tools/media.py. Every column but the last is computed from the
# file, so nothing in it can quietly drift; tools/check.py C21 fails when it
# does. The caption is the one column written by hand, and it is carried over
# whenever this file is regenerated.
#
# Rebuild after adding or removing media:   python3 tools/media.py scan
# Check without rewriting anything:         python3 tools/media.py verify
#
#   path      relative to the top of the repository
#   kind      photo, image, video, document or model
#   bytes     size on disk
#   pixels    WIDTHxHEIGHT as stored, before any EXIF rotation is applied
#   captured  local time the shutter opened, or the recording started.
#             Blank where a file was made rather than shot.
#   made      local time THIS version was written, where that differs from the
#             capture: a photograph marked up afterwards, or an export that
#             carries no capture time at all. Blank when the two agree, which
#             is the normal case. It is here because the file name's tHHMM
#             token may follow either one, and C23 has to be able to tell a
#             real timestamp from an invented one.
#             Where a token-bearing file has no timestamp inside it at all, as
#             the PNG exports do, this was recovered once from the modification
#             time and is preserved verbatim from then on: a clone resets
#             mtimes, so reading it twice would give two different answers.
#   sha256    of the file as it stands. This is the integrity baseline.
#   caption   what the file shows, in one line.
#
# What is NOT here, and where it lives instead:
#   00_inbox/          untracked staging, nothing filed yet
#   01_survey/         the deliverable, whose freshness is 01_survey/DERIVED.txt
#   qr-survey.*        regenerated from the published URL, see MAINTENANCE.md
#   CONTACT-SHEET.jpg  generated from these rows, so listing it here would make
#                      the manifest describe its own output
"""


# ---------------------------------------------------------------- file facts
def jpeg_pixels(path):
    with open(path, "rb") as f:
        d = f.read()
    i = 2
    while i + 9 < len(d):
        if d[i] != 0xFF:
            i += 1
            continue
        m = d[i + 1]
        if m in (0xC0, 0xC1, 0xC2, 0xC3, 0xC5, 0xC6, 0xC7, 0xC9, 0xCA, 0xCB, 0xCD, 0xCE, 0xCF):
            h, w = struct.unpack(">HH", d[i + 5:i + 9])
            return w, h
        if m in (0xD8, 0xD9) or 0xD0 <= m <= 0xD7:
            i += 2
            continue
        i += 2 + struct.unpack(">H", d[i + 2:i + 4])[0]
    return None


def png_pixels(path):
    with open(path, "rb") as f:
        d = f.read(24)
    return struct.unpack(">II", d[16:24]) if d[:8] == b"\x89PNG\r\n\x1a\n" else None


def pixels(path):
    ext = os.path.splitext(path)[1].lower()
    try:
        if ext in (".jpg", ".jpeg"):
            return jpeg_pixels(path)
        if ext == ".png":
            return png_pixels(path)
        if ext in (".webp", ".gif", ".tif", ".tiff"):
            from PIL import Image
            with Image.open(path) as im:
                return im.size
    except Exception:
        return None
    return None


def from_meta(path, meta):
    """Video and anything else this file cannot parse: take the size exiftool read."""
    o = meta.get(os.path.abspath(path), {})
    try:
        return int(o["ImageWidth"]), int(o["ImageHeight"])
    except (KeyError, TypeError, ValueError):
        return None


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def exiftool(paths, tags):
    """One subprocess for the whole library. Returns {path: {tag: value}}."""
    if not paths:
        return {}
    args = ["exiftool", "-q", "-q", "-n", "-S"] + ["-" + t for t in tags] + ["-j"] + paths
    try:
        r = subprocess.run(args, capture_output=True, text=True)
        if r.returncode not in (0, 1) or not r.stdout.strip():
            return {}
        import json
        return {os.path.abspath(o["SourceFile"]): o for o in json.loads(r.stdout)}
    except (FileNotFoundError, ValueError):
        return {}


def captured(path, meta):
    """Local wall-clock time the shutter opened, or the recording started.

    Stills carry DateTimeOriginal in local time already. MP4 CreateDate is UTC
    and marks the END of the recording, which is why the file name token on a
    35-second clip is a minute earlier than the tag; subtracting the duration
    and shifting to local time reproduces the token exactly.
    """
    o = meta.get(os.path.abspath(path), {})
    dto = o.get("DateTimeOriginal") or o.get("SubSecDateTimeOriginal")
    if dto:
        return str(dto)[:19].replace(":", "-", 2)
    create = o.get("CreateDate")
    if create and path.lower().endswith(".mp4"):
        try:
            t = datetime.datetime.strptime(str(create)[:19], "%Y:%m:%d %H:%M:%S")
            t -= datetime.timedelta(seconds=float(o.get("Duration") or 0))
            local = t.replace(tzinfo=datetime.timezone.utc).astimezone()
            return local.strftime("%Y-%m-%d %H:%M:%S")
        except (ValueError, TypeError):
            return ""
    return ""


def orientation(path, meta):
    o = meta.get(os.path.abspath(path), {}).get("Orientation")
    try:
        return int(o)
    except (TypeError, ValueError):
        return None


def made(path, meta, capture):
    """When this version of the file was written, if that is later than capture.

    06_drawings/01 is the case this exists for: a frame shot at 19:41 and drawn
    on until 19:46. The drawing is what the file is, so its name carries 19:46,
    and without this column that token looks invented.
    """
    o = meta.get(os.path.abspath(path), {})
    mod = str(o.get("ModifyDate") or "")[:19].replace(":", "-", 2)
    return mod if mod and capture and mod > capture else ""


# ------------------------------------------------------------------ the walk
def media_files():
    out = []
    for dp, dns, fns in os.walk(ROOT):
        dns[:] = sorted(d for d in dns if d not in SKIP_DIRS)
        for fn in sorted(fns):
            if fn.startswith(".") or fn == SHEET:
                continue
            rel = os.path.relpath(os.path.join(dp, fn), ROOT)
            if os.path.dirname(rel) and os.path.splitext(fn)[1].lower() in MEDIA_EXT:
                out.append(rel)
    return sorted(out)


def read_manifest():
    """Returns (rows, captions, kept).

    "kept" is the made-times of files that carry no timestamp inside them,
    which scan preserves rather than recomputing. See recovered_time().
    A missing manifest is not an error: scan creates it.
    """
    rows, captions, kept = [], {}, {}
    if not os.path.exists(MANIFEST):
        return rows, captions, kept
    with open(MANIFEST, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if parts[0] == "path":
                continue
            parts += [""] * (len(COLUMNS) - len(parts))
            row = dict(zip(COLUMNS, parts[:len(COLUMNS)]))
            rows.append(row)
            if row["caption"]:
                captions[row["path"]] = row["caption"]
            if row["made"] and not row["captured"]:
                kept[row["path"]] = row["made"]
    return rows, captions, kept


TOKEN_RE = re.compile(r"_t\d{4}\.[a-z0-9]+$")


def recovered_time(path, kept):
    """For a token-bearing file with no timestamp inside it, when it was made.

    The PNG exports in 06_drawings are the case. A PNG carries no EXIF, so the
    only evidence of when one was written is its modification time, and a git
    clone resets that to the moment of checkout. The recovery is therefore
    one-way: read the mtime while it still means something, write it here, and
    never read it again. Once a value is in the manifest it is preserved
    verbatim, which is what makes the tHHMM token on those files checkable in a
    fresh clone rather than merely plausible.

    Only files whose name carries a tHHMM token get one. Everything else has
    nothing to check the value against, and a modification time with no claim
    resting on it is not a fact worth recording: the GLB's reads 1979, which it
    inherited from the zip it arrived in.
    """
    rel = os.path.relpath(path, ROOT)
    if rel in kept:
        return kept[rel]
    if not TOKEN_RE.search(rel):
        return ""
    return datetime.datetime.fromtimestamp(os.path.getmtime(path)).strftime("%Y-%m-%d %H:%M:%S")


def build_rows(captions, kept):
    files = media_files()
    meta = exiftool([os.path.join(ROOT, f) for f in files],
                    ("DateTimeOriginal", "CreateDate", "ModifyDate", "Duration",
                     "Orientation", "ImageWidth", "ImageHeight"))
    rows = []
    for rel in files:
        p = os.path.join(ROOT, rel)
        wh = pixels(p) or from_meta(p, meta)
        shot = captured(p, meta)
        rows.append({
            "path": rel,
            "kind": MEDIA_EXT[os.path.splitext(rel)[1].lower()],
            "bytes": str(os.path.getsize(p)),
            "pixels": "%dx%d" % wh if wh else "",
            "captured": shot,
            "made": made(p, meta, shot) or ("" if shot else recovered_time(p, kept)),
            "sha256": sha256(p),
            "caption": captions.get(rel, ""),
        })
    return rows


def write_manifest(rows):
    with open(MANIFEST, "w", encoding="utf-8") as f:
        f.write(HEADER)
        f.write("\t".join(COLUMNS) + "\n")
        for r in rows:
            f.write("\t".join(r[c] for c in COLUMNS) + "\n")


# ------------------------------------------------------------------ commands
def cmd_scan():
    old_rows, captions, kept = read_manifest()
    rows = build_rows(captions, kept)
    write_manifest(rows)
    was = {r["path"] for r in old_rows}
    now = {r["path"] for r in rows}
    for p in sorted(now - was):
        print("  added    %s" % p)
    for p in sorted(was - now):
        print("  gone     %s" % p)
    missing = [r["path"] for r in rows if not r["caption"]]
    print("  %d file(s), %.0f MB" % (len(rows), sum(int(r["bytes"]) for r in rows) / 1024 ** 2))
    if missing:
        print("  %d without a caption. Write one in MEDIA.tsv:" % len(missing))
        for p in missing[:12]:
            print("      %s" % p)
    return 0


def cmd_verify():
    rows, _, _ = read_manifest()
    listed = {r["path"]: r for r in rows}
    disk = set(media_files())
    bad = []
    for p in sorted(disk - set(listed)):
        bad.append("%s is on disk with no row in MEDIA.tsv" % p)
    for p in sorted(set(listed) - disk):
        bad.append("MEDIA.tsv lists %s, which is not on disk" % p)
    for p in sorted(disk & set(listed)):
        r, full = listed[p], os.path.join(ROOT, p)
        if str(os.path.getsize(full)) != r["bytes"]:
            bad.append("%s is %s bytes, the manifest says %s" % (p, os.path.getsize(full), r["bytes"]))
        elif sha256(full) != r["sha256"]:
            bad.append("%s has changed: its sha256 no longer matches the manifest" % p)
        if not r["caption"]:
            bad.append("%s has no caption" % p)
    for line in bad:
        print("  %s" % line)
    print("  %d problem(s)" % len(bad) if bad else "  manifest and disk agree")
    return 1 if bad else 0


def sheet_digest(rows):
    """What a folder's contact sheet was built from, as one hash.

    A sheet is derived, so it goes stale the moment a photograph is added,
    replaced or removed, and a stale sheet does not look wrong: it just quietly
    omits the picture you were looking for. This digest goes into the JPEG's
    own comment when the sheet is written, and C22 recomputes it from the
    folder and compares. Same idea as DERIVED.txt, carried in the file itself
    because a contact sheet needs no second place to be remembered.
    """
    body = "\n".join("%s %s" % (os.path.basename(r["path"]), r["sha256"][:16]) for r in rows)
    return hashlib.sha256(body.encode()).hexdigest()


def read_sheet_digest(path):
    """The digest out of a JPEG COM marker, without needing Pillow."""
    try:
        with open(path, "rb") as f:
            d = f.read(1 << 16)
    except OSError:
        return None
    i = 2
    while i + 4 < len(d):
        if d[i] != 0xFF:
            return None
        m = d[i + 1]
        if m == 0xDA:                       # start of scan, no comment before it
            return None
        n = struct.unpack(">H", d[i + 2:i + 4])[0]
        if m == 0xFE:                       # COM
            text = d[i + 4:i + 2 + n].decode("ascii", "replace")
            if text.startswith(SHEET_TAG):
                return text[len(SHEET_TAG):].strip()
        i += 2 + n
    return None


def cmd_sheets():
    """One JPEG per media folder, every image in it, numbered by its index.

    Derived and cheap to rebuild, which is why it is not in MEDIA.tsv: a file
    generated from the manifest has no business being described by it.
    """
    try:
        from PIL import Image, ImageDraw, ImageFont, ImageOps
    except ImportError:
        print("  needs Pillow:  python3 -m pip install Pillow")
        return 1
    rows, _, _ = read_manifest()
    by_dir = {}
    for r in rows:
        if r["kind"] in ("photo", "image") and r["pixels"]:
            by_dir.setdefault(os.path.dirname(r["path"]), []).append(r)
    font = None
    for f in ("/System/Library/Fonts/Supplemental/Arial Bold.ttf",
              "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"):
        if os.path.exists(f):
            font = ImageFont.truetype(f, 26)
            break
    font = font or ImageFont.load_default()

    CELL, LABEL, COLS, PAD = 300, 32, 6, 6
    for d, items in sorted(by_dir.items()):
        if not d or len(items) < 2:
            continue
        cols = min(COLS, len(items))
        rowsn = (len(items) + cols - 1) // cols
        sheet = Image.new("RGB", (cols * CELL, rowsn * (CELL + LABEL)), "#FFFFFF")
        draw = ImageDraw.Draw(sheet)
        for i, r in enumerate(items):
            x, y = (i % cols) * CELL, (i // cols) * (CELL + LABEL)
            try:
                with Image.open(os.path.join(ROOT, r["path"])) as im:
                    im = ImageOps.exif_transpose(im).convert("RGB")
                    im.thumbnail((CELL - 2 * PAD, CELL - 2 * PAD), Image.LANCZOS)
                    sheet.paste(im, (x + (CELL - im.width) // 2, y + LABEL + (CELL - 2 * PAD - im.height) // 2 + PAD))
            except Exception:
                draw.line([x + PAD, y + LABEL, x + CELL - PAD, y + CELL], fill="#CCCCCC")
            draw.text((x + PAD, y + 5), os.path.basename(r["path"])[:2], fill="#1B2124", font=font)
            draw.rectangle([x, y, x + CELL - 1, y + CELL + LABEL - 1], outline="#C9D0D3")
        out = os.path.join(ROOT, d, SHEET)
        sheet.save(out, quality=76, optimize=True, progressive=True,
                   comment=(SHEET_TAG + sheet_digest(items)).encode("ascii"))
        print("  %-20s %2d images  %4.0f KB" % (d + "/", len(items), os.path.getsize(out) / 1024))
    return 0


def cmd_show(prefix):
    rows, _, _ = read_manifest()
    hit = [r for r in rows if r["path"].startswith(prefix) or r["path"].split("/")[0].startswith(prefix)]
    if not hit:
        print("  nothing under %r" % prefix)
        return 1
    for r in hit:
        print("  %-58s %s" % (os.path.basename(r["path"]), r["caption"]))
    return 0


USAGE = __doc__.split("Why this exists")[0].rstrip()

if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    if cmd == "scan":
        sys.exit(cmd_scan())
    if cmd == "verify":
        sys.exit(cmd_verify())
    if cmd == "sheets":
        sys.exit(cmd_sheets())
    if cmd == "show":
        sys.exit(cmd_show(sys.argv[2] if len(sys.argv) > 2 else ""))
    print(USAGE)
    sys.exit(2)
